[package]
authors.workspace = true
edition.workspace = true
name = "vulk-test"
version = "0.1.0"

[dependencies]
vulk = { path = "../vulk" }

anyhow.workspace = true
env_logger.workspace = true
glam.workspace = true
imagelib.workspace = true
log.workspace = true
palette.workspace = true
rand.workspace = true
rand_pcg.workspace = true
ron.workspace = true
serde.workspace = true
shaderc.workspace = true
